import {Platform, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  gradientOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#FFFFFF',
    opacity: 0.45,
    pointerEvents: 'none',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 56 : 24,
    paddingBottom: 16,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  undoButton: {
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  undoButtonDisabled: {
    opacity: 0.4,
  },
  undoText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#20B2AA',
  },
  undoTextDisabled: {
    color: '#999',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#000',
  },
  doneButton: {
    paddingVertical: 6,
    paddingHorizontal: 4,
  },
  doneText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#20B2AA',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 4,
    paddingBottom: 16,
  },
  previewSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 8,
  },
  toolbarDock: {
    backgroundColor: '#F5F5F5',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#E0E0E0',
  },
  previewCard: {
    alignSelf: 'center',
    width: '100%',
    maxWidth: 340,
    aspectRatio: 4 / 5,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  previewInner: {
    backgroundColor: '#111',
    overflow: 'hidden',
  },
  mediaFill: {
    ...StyleSheet.absoluteFillObject,
  },
  imageStage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageTransformWrap: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  cropImage: {
    width: '100%',
    height: '100%',
  },
  cropDimPanel: {
    position: 'absolute',
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
  cropFrame: {
    position: 'absolute',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
  },
  cropCorner: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderColor: '#FFFFFF',
  },
  cropCornerTL: {
    top: -1,
    left: -1,
    borderTopWidth: 3,
    borderLeftWidth: 3,
  },
  cropCornerTR: {
    top: -1,
    right: -1,
    borderTopWidth: 3,
    borderRightWidth: 3,
  },
  cropCornerBL: {
    bottom: -1,
    left: -1,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
  },
  cropCornerBR: {
    bottom: -1,
    right: -1,
    borderBottomWidth: 3,
    borderRightWidth: 3,
  },
  cropControls: {
    marginTop: 14,
    paddingHorizontal: 8,
  },
  cropHint: {
    textAlign: 'center',
    fontSize: 12,
    color: '#666',
    marginBottom: 10,
  },
  aspectRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 4,
  },
  aspectChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#E8E8E8',
  },
  aspectChipActive: {
    backgroundColor: '#20B2AA',
  },
  aspectChipText: {
    fontSize: 12,
    color: '#333',
    fontWeight: '500',
  },
  aspectChipTextActive: {
    color: '#FFF',
  },
  resetChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#CCC',
  },
  resetChipText: {
    fontSize: 12,
    color: '#333',
    fontWeight: '500',
  },
  textStylePanel: {
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: '#FFF',
    borderRadius: 10,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  textStyleSectionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#333',
    marginBottom: 6,
    marginTop: 2,
  },
  colorRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  colorSwatch: {
    width: 26,
    height: 26,
    borderRadius: 13,
  },
  colorSwatchBorder: {
    borderWidth: 1,
    borderColor: '#DDD',
  },
  colorSwatchSelected: {
    borderWidth: 3,
    borderColor: '#20B2AA',
  },
  sizeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 8,
  },
  sizeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sizeValue: {
    fontSize: 14,
    fontWeight: '600',
    color: '#000',
    minWidth: 28,
    textAlign: 'center',
  },
  opacityRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 2,
  },
  opacityChip: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    backgroundColor: '#F0F0F0',
  },
  opacityChipActive: {
    backgroundColor: '#20B2AA',
  },
  opacityChipText: {
    fontSize: 12,
    color: '#333',
    fontWeight: '500',
  },
  opacityChipTextActive: {
    color: '#FFF',
  },
  bgToggleRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  bgToggleChip: {
    flex: 1,
    paddingVertical: 7,
    borderRadius: 8,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
  },
  bgToggleChipActive: {
    backgroundColor: '#20B2AA',
  },
  bgToggleChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#333',
  },
  bgToggleChipTextActive: {
    color: '#FFF',
  },
  colorPickerTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    marginBottom: 8,
  },
  colorPickerSwatch: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#DDD',
  },
  colorPickerTriggerTextWrap: {
    flex: 1,
    marginLeft: 10,
  },
  colorPickerTriggerLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#333',
  },
  colorPickerTriggerValue: {
    fontSize: 12,
    color: '#666',
    marginTop: 2,
  },
  colorPickerTriggerAction: {
    fontSize: 12,
    fontWeight: '600',
    color: '#20B2AA',
  },
  colorPickerBackdrop: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  colorPickerBackdropPress: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  colorPickerModal: {
    backgroundColor: '#FFF',
    borderRadius: 14,
    padding: 16,
    zIndex: 2,
    elevation: 8,
  },
  colorPickerModalTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111',
    marginBottom: 12,
  },
  colorPickerPreview: {
    height: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E5E5',
    marginBottom: 12,
  },
  colorPickerSvPanel: {
    height: 150,
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 12,
  },
  colorPickerSvBase: {
    ...StyleSheet.absoluteFillObject,
  },
  colorPickerSvOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  colorPickerThumb: {
    position: 'absolute',
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#FFF',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.25,
    shadowRadius: 2,
    elevation: 3,
  },
  colorPickerHueTrack: {
    height: 22,
    borderRadius: 11,
    overflow: 'hidden',
    marginBottom: 12,
    justifyContent: 'center',
  },
  colorPickerHueGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  colorPickerHueThumb: {
    position: 'absolute',
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#FFF',
    top: 0,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 3,
  },
  colorPickerHexRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    borderRadius: 10,
    paddingHorizontal: 10,
    marginBottom: 14,
    height: 42,
  },
  colorPickerHexLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginRight: 4,
  },
  colorPickerHexInput: {
    flex: 1,
    fontSize: 15,
    color: '#111',
    padding: 0,
  },
  colorPickerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  colorPickerCancelButton: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorPickerCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  colorPickerApplyButton: {
    flex: 1,
    height: 42,
    borderRadius: 10,
    backgroundColor: '#20B2AA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorPickerApplyText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFF',
  },
  textOverlayBox: {
    position: 'absolute',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minWidth: 80,
    overflow: 'hidden',
    zIndex: 5,
  },
  textOverlayBoxExport: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
  },
  textOverlayExportText: {
    textAlign: 'center',
    width: '100%',
  },
  textOverlayInput: {
    textAlign: 'center',
    padding: 0,
    margin: 0,
    minHeight: 28,
  },
  textDragHandle: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 4,
    paddingBottom: 6,
    marginBottom: 4,
    marginHorizontal: -12,
    marginTop: -10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  videoControls: {
    position: 'absolute',
    bottom: 12,
    alignSelf: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  videoControlText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '600',
  },
  toolbar: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 48,
    paddingBottom: Platform.OS === 'ios' ? 16 : 12,
    paddingTop: 10,
  },
  toolButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 56,
  },
  toolIconWrap: {
    marginBottom: 3,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toolLabel: {
    fontSize: 11,
    color: '#000',
    fontWeight: '500',
  },
  toolLabelActive: {
    color: '#20B2AA',
    fontWeight: '700',
  },
  serifA: {
    fontSize: 22,
    fontWeight: '400',
    color: '#000',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    lineHeight: 24,
  },
  serifAActive: {
    color: '#20B2AA',
  },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 20,
  },
  queueIndicator: {
    textAlign: 'center',
    marginTop: 8,
    fontSize: 12,
    color: '#666',
  },
});

export default styles;
