#!/bin/bash
set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Cleaning iOS build artifacts..."

# Clean Xcode derived data
rm -rf ~/Library/Developer/Xcode/DerivedData/Alenga-*

# Clean build directory (contains codegen output - will be regenerated by pod install)
rm -rf build

echo "Regenerating codegen (RCTAppDependencyProvider, etc.)..."
pod install

echo "Clean complete! You can now build with 'yarn ios' or from Xcode."
