const endpoints = {
  auth: {
    login: '/login',
    signup: '/signup',
    forgotPassword: '/forget-password',
    verifyOtp: '/verify-code',
    resetPassword: '/set-password',
    logout: '/logout',
  },
  home: {
    feedPost: '/get-newsfeed',
    profileById: '/get-user',
    createPost: '/post/create',
    updatePost: '/post/update',
    deletePost: '/post/delete',
    reportPost: '/report/create',
    myPost: '/get-user',
    getBlockedUser: 'get-blocked-users',
    block: '/block-user',
    unBlock: '/unblock-user',
    followRequest: '/get-follow-requests',
    followers: '/get-followers',
    following: '/get-following',
    follow: '/follow-user',
    unFollow: '/unfollow-user',
    acceptFollow: '/accept-follow-request',
    rejectFollow: '/reject-follow-request',
    countries: '/countries',
    state: '/states',
    city: '/cities',
    notifications: '/notifications',
    markRead: '/mark-as-read',
  },
  profile: {
    editProfile: '/edit-profile',
    getProfile: '/profile',
    changePassword: '/change-password',
  },
  subscription: {
    getSubscription: '/get-subscription-plans',
    getSubscriptionLogs: '/get-subscription-logs',
    subscribe: '/subscribe',
  },
  shop: {
    allShop: '/shops',
    createShop: '/shop/create',
    shopDetail: '/shop',
    updateShop: '/shop/update',
  },
  products: {
    productDetail: '/product',
    category: '/categories',
    cart: '/add-to-cart',
    getCart: '/get-cart',
    removeCartItem: '/remove-from-cart',
    updateCart: '/update-cart',
    checkout: '/order/checkout',
    deleteProductImage: '/product',
    ordersList: '/get-orders',
    orderDetail: '/get-order-detail',
    shopOrders: '/get-shop-orders',
    paymentLogs: '/get-payment-logs',
    similar: '/product',
    acceptOrder:'get-order-detail/'
  },
  education: {
    getArticles: '/articles',
    getBlogs: '/blogs',
    getVideos: '/videos',
    getBlog: '/blog',
    getArticle: '/article',
    getVideo: '/video',
    similarVideos: '/video',
    getMyBlogs: '/blogs/current-user',
    getMyArticles: '/articles/current-user',
    getMyVideos: '/videos/current-user',
    createArticle: '/article/create',
    createBlog: '/blog/create',
    createVideo: '/video/create',
    updateArticleStatus: '/article/update-status',
    updateBlogStatus: '/blog/update-status',
    updateBlog: '/blog/update',
    updateArticle: '/article/update',
    updateVideo: '/video/update',
  },
  chat: {
    chatList: '/get-chat-list',
  },
  menu: {
    getSavedItems: '/get-saved-items',
    saveItem: '/save-item',
    removeSaved: '/remove-saved-item',
    aboutUs: '/content?type=aboutUs',
    contactUs: '/contact-us',
    banks: '/banks',
    updateBank: '/bank/update',
    createBank: '/bank/create',
  },
};

export default endpoints;
