const endpoints = {
  auth: {
    login: '/login',
    signup: '/signup',
    signupSeller: '/signup-seller',
    forgotPassword: '/forget-password',
    verifyOtp: '/verify-code',
    resetPassword: '/set-password',
    logout: '/logout',
  },
  home: {
    feedPost: '/get-newsfeed',
    profileById: '/get-user',
    createPost: '/post/create',
    updatePost: '/post/update',
    mediaDelete: '/post',
    deletePost: '/post/delete',
    reportPost: '/report/create',
    myPost: '/get-user',
    getBlockedUser: 'get-blocked-users',
    block: '/block-user',
    unBlock: '/unblock-user',
    followRequest: '/get-follow-requests',
    followers: '/get-followers',
    following: '/get-following',
    follow: '/follow-user',
    removeFollower: '/remove-follower',
    unFollow: '/unfollow-user',
    acceptFollow: '/accept-follow-request',
    rejectFollow: '/reject-follow-request',
    countries: '/countries',
    state: '/states',
    city: '/cities',
    notifications: '/notifications',
    markRead: '/mark-as-read',
    markAllRead: '/mark-all-as-read',
    allUsers: '/search-users',
    videos: 'videos',
  },
  profile: {
    editProfile: '/edit-profile',
    getProfile: '/profile',
    changePassword: '/change-password',
    deleteAccount: '/delete-my-account',
    getUserPosts: '/get-user/{id}/posts',
  },
  subscription: {
    getSubscription: '/get-subscription-plans',
    getSubscriptionLogs: '/get-subscription-logs',
    subscribe: '/subscribe',
  },
  shop: {
    allShop: '/shops',
    createShop: '/shop/create',
    shopDetail: '/shop',
    updateShop: '/shop/update',
    isSeller: '/user/shops',
  },
  products: {
    productDetail: '/product',
    category: '/categories',
    cart: '/add-to-cart',
    getCart: '/get-cart',
    removeCartItem: '/remove-from-cart',
    updateCart: '/update-cart',
    checkout: '/order/checkout',
    deleteProductImage: '/product',
    ordersList: '/get-orders',
    orderDetail: '/get-order-detail',
    shopOrders: '/get-shop-orders',
    paymentLogs: '/get-payment-logs',
    similar: '/product',
    acceptOrder: 'get-order-detail/',
    recommended: '/products/recommended',
    allProducts: '/products',
  },
  education: {
    getArticles: '/articles',
    getBlogs: '/blogs',
    getVideos: '/videos',
    getBlog: '/blog',
    getArticle: '/article',
    getVideo: '/video',
    similarVideos: '/video',
    getMyBlogs: '/blogs/current-user',
    getMyArticles: '/articles/current-user',
    getMyVideos: '/videos/current-user',
    createArticle: '/article/create',
    createBlog: '/blog/create',
    createVideo: '/video/create',
    updateArticleStatus: '/article/update-status',
    updateBlogStatus: '/blog/update-status',
    updateVideoStatus: '/video/update-status',
    updateBlog: '/blog/update',
    updateArticle: '/article/update',
    updateVideo: '/video/update',
  },
  chat: {
    chatList: '/get-chat-list',
    create: '/create-chat',
    fetchConversation: '/get-chat-list',
    createGroup: '/create-group',
    fetchChat: '/get-chat',
    send: '/send-message',
    getSignature: '/get-signature',
  },
  menu: {
    getSavedItems: '/get-saved-items',
    saveItem: '/save-item',
    removeSaved: '/remove-saved-item',
    aboutUs: '/content?type=aboutUs',
    contactUs: '/contact-us',
    banks: '/banks',
    updateBank: '/bank/update',
    createBank: '/bank/create',
  },

  stories: {
    getStories: '/stories',
    addStories: '/stories',
  },
  liveStream: {
    getLiveStreams: '/live-stream',
    createLiveStreams: '/live-stream/start',
    endLiveStreams: '/live-stream/end',
    getToken: '/live-stream/getToken',
    getUsers: '/live-stream/users',
  },
  rider: {
    submitApplication: '/rider/submit-application',
  },
  settings: {
    privacy: '/privacy/settings',
    notifications: '/notifications/delivery-preferences',
    sellerSettings: '/seller/settings',
    changePassword: '/change-password',
    deleteAccount: '/delete-my-account',
  },
  bidding: {
    settings: '/bidding/settings',
    placeBid: '/bids',
  },
  search: {
    users: '/search-users',
    auctions: '/auctions',
    products: '/products',
    shops: '/shops',
    articles: '/articles',
    userArticles: '/articles/current-user',
    blogs: '/blogs',
    userBlogs: '/blogs/current-user',
    videos: '/videos',
    userVideos: '/videos/current-user',
    chats: '/get-chat-list',
    shopProducts: '/shop/{shop_id}/products',
  },
};

export default endpoints;
