export const images = {
  VisibilityOffIcon: require('../assets/Icons/visibilityofficon.png'),
  EyeIcon: require('../assets/Icons/eyeicon.png'),
  profile: require('../assets/Icons/profile.png'),
  camera: require('../assets/Icons/camera.png'),
  checkedIcon: require('../assets/Icons/checkedIcon.png'),
  linearCircle: require('../assets/Icons/linearCircle.png'),
  linearCircle2: require('../assets/Icons/linearCircle2.png'),
  bellicon: require('../assets/Icons/bellicon.png'),
  callIcon: require('../assets/Icons/callIcon.png'),
  videoIcon: require('../assets/Icons/videoIcon.png'),
  searchIcon: require('../assets/Icons/searchIcon.png'),
  search: require('../assets/Icons/search.png'),
  media: require('../assets/Icons/media.png'),
  video: require('../assets/Icons/video.png'),
  user: require('../assets/Icons/user.png'),
  user2: require('../assets/Icons/user2.png'),
  postImage1: require('../assets/Icons/postImage1.png'),
  heartIcon: require('../assets/Icons/heartIcon.png'),
  like: require('../assets/Icons/like.png'),
  likeFill: require('../assets/Icons/likeFill.png'),
  share: require('../assets/Icons/share.png'),
  comment: require('../assets/Icons/comment.png'),
  save: require('../assets/Icons/save.png'),
  dots: require('../assets/Icons/dots.png'),
  postImage2: require('../assets/Icons/postImage2.png'),
  ratingstaricon: require('../assets/Icons/ratingstaricon.png'),
  home: require('../assets/Icons/Home.png'),
  menu: require('../assets/Icons/menu.png'),
  game: require('../assets/Icons/game.png'),
  market: require('../assets/Icons/market.png'),
  backicon: require('../assets/Icons/backicon.png'),
  lock: require('../assets/Icons/lock.png'),
  qmark: require('../assets/Icons/qmark.png'),
  send: require('../assets/Icons/send.png'),
  notifi: require('../assets/Icons/notifi.png'),
  request: require('../assets/Icons/request.png'),
  plan: require('../assets/Icons/plan.png'),
  blogs: require('../assets/Icons/blogs.png'),
  phone: require('../assets/Icons/phone.png'),
  help: require('../assets/Icons/help.png'),
  logout: require('../assets/Icons/logout.png'),
  chatIcon: require('../assets/Icons/chatIcon.png'),
  pro1: require('../assets/Icons/pro1.png'),
  pro2: require('../assets/Icons/pro2.png'),
  pro3: require('../assets/Icons/pro3.png'),
  filter: require('../assets/Icons/filter.png'),
  noti: require('../assets/Icons/noti.png'),
  bin: require('../assets/Icons/bin.png'),
  blog1: require('../assets/Icons/blog1.png'),
  upload: require('../assets/Icons/upload.png'),
  edit: require('../assets/Icons/edit.png'),
  recordingIcon: require('../assets/Icons/recordingIcon.png'),
  face: require('../assets/Icons/face.png'),
  calendericon: require('../assets/Icons/calendericon.png'),
  cross: require('../assets/Icons/cross.png'),
  unsave: require('../assets/Icons/unsave.png'),
  unfillHeart: require('../assets/Icons/unfillHeart.png'),

  //Imagesssss/////
  shop1: require('../assets/images/shop1.png'),
  shop11: require('../assets/images/shop11.png'),
  shop2: require('../assets/images/shop2.png'),
  shop3: require('../assets/images/shop3.png'),
  shop4: require('../assets/images/shop4.png'),
  shop5: require('../assets/images/shop5.png'),
  shop6: require('../assets/images/shop6.png'),
  profileBg: require('../assets/images/profileBg.png'),



};
